home-assistant:
    country: ENC[AES256_GCM,data:nLk=,iv:bjnWZHY0mZ2cJ+rVxDokwXYEEFispCJ+Ce4W9EBcjHU=,tag:PD4A3MaPulsa7LfIevFI/A==,type:str]
    time_zone: ENC[AES256_GCM,data:cana8JugFt++PRp0X8HKfg==,iv:GxXRe/zpEAaZ8PHj3cWZUUGMDFEXdS+sCjIrABiX5Rk=,tag:LoMsv+rmH9VfZEtnogFzWA==,type:str]
    latitude: ENC[AES256_GCM,data:djPp81Cg/NRlVgKzsL8Zd+A=,iv:TYeJH5jGIvoGwA/aOuAT6xRirb6uDr85UWzscnlw1RU=,tag:p3ZMZ0DOOstzCNRqu6daMw==,type:str]
    longitude: ENC[AES256_GCM,data:Yp8S3jSY/Uhvw+1HVR/9QEU=,iv:Ha4u8DOhe+xOCWv8lPgTgFFk07DgU3jQ5knDCdanXHQ=,tag:QbJ3/GdReqw2ofvI4jAf4g==,type:str]
sops:
    age:
        - recipient: age1jcvl947fgdrxylahyfh3msqsyjp3twd36fgld2jsnxngm0m2agtqynfn29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ck5pWXBXemFVK1lFNnA1
            bUprVmIxZjl2NWk1M3g4bW0wQXY3aHFRZDBvCnhabEIzeFd0ajkrVWF2MUNuV0R0
            dUhTOEFzWWpaeEo5TS9ndHpnREhEZVkKLS0tIG54NGg3U3JKRVIvQTd4QlhBYkRR
            QkJJRGd2TGE1WFBrQWI1cy9za0M4UmsKquy1klx7gT4+oH8x+f7dAFmoA0EPc7vi
            EMBPAzJ9uQQm3pFr4C26VEkakqqoweasmorUtxlraV9R8PMfCLcs0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T17:21:41Z"
    mac: ENC[AES256_GCM,data:DSsBFzxXAJN089CKjR1r7zDB3EDPbGhCgcj8iRLf6Xnm6VWzxieHfJygY3TN+fIBUMEqEr94XV/esWS4NKRU71hh+TBZgxpsTiPpU8mXvd7Kmx/TtgtIBRJQ1EwByAtgVcmGmtroshO8c/txOV3I/pa8FyHm0UslcXOTdh1X23A=,iv:c9oaSUdtOtJamDLSg8e8cp0+qw7e0dDYHOv7qAz8SQA=,tag:xgbrcs5FbxSwtV7bAQ82cg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
