cloudflared:
    cert: ENC[AES256_GCM,data:KzJjQMElaueAJ/lix+aDWhcNBGvroIK3aQVcO0CRlrwfRDHH80H2SFOlhND82NuWL+9kLv+iUZrwtP4U2p0RI3aTCc0DefRnqeOLrvbJRO2qUli2K91kycvAETe3l5kJpqc5tjD4Qoj8Un57K8YqaJQpnSHl1bf8ro9qWVhzDjpwY0+F52vWz0SOXy7/1oplhzl6HSqgcsqYs+7KfCHpB6+ciO+iLhshui8g1gj2IozUNtWVrILkjbkpkxKskBmExO4xnd6YziFItyukQu5MOvpq/7/WhiJd6eXAQHpkpOjH546H20D6GBMspbIz/CccmhTTWAySRxsfB6UMqZxkwTv+zvyOezngMu+gXIqnI3JR1gns4ugBkm76xO6xTWCtigiNC4mm4E3OKeQPLSIui/aMr7rXDN9t2Rd2zlVXW+rTxd0519ZzrUNMn/BYjpzUL6WVUFRcbbNkFxDRyp0++4LVCX9hw+HOTGQ36jAf3LE=,iv:sGb34RxtRO4+eGnTkiTmnBex1QZxxFyXr9zc3nuONYE=,tag:/iiiRoAfialOkljwSj0fPQ==,type:str]
sops:
    age:
        - recipient: age14s2zpggxlstlerglhfw5jh9ytcth73gpkpmm36d7am95f0y5pp8srqq0f6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWmdLbG1SRGlJTkR3V09u
            U3VQMUxBQ0sxWVp1dGJlWFZWVmhkSVl3T2s4CnJXK2phajNDRzdsazZtcVNxQXJC
            YVN4Y0g0SG40cjh0ZGgyVk9FQ1FFY0UKLS0tIE5nRHVDbGZIdEl3REpzbFRXOU9H
            WDNMM1dNVUVydVpkMHJSaGQ0Yk5KcG8Km+edcrWXBcUlU93A8zsNdMuH9esBC0SJ
            eOGrFUHn6P6qWN11u6cAoxQpV3ljvRM5M3NPrTtKBQHRJn5uHrw7dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T13:05:13Z"
    mac: ENC[AES256_GCM,data:+m+6+V8B8VgPo88XboW/9LLtPEeAty52o6iwaWwN3yLN5CtDj43aOPClheYv0b685UPP4Ga7+Gb8dRC8/e/puuC0+dGO2z6NGNFSxoBeZ4mTH7NhLBO1h8O1ciV9ssZ30r6XwaiY2kYbkHh/b4OYRuSTEw55moKYlr2noZOAOB0=,iv:KgLqyqkhzHyV5SmdEJfLTR1zsmRS2PAQaVRdUw+3scA=,tag:TnAJC9UOL60QNqGVmbjlUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
