home_assistant:
    timezone: ENC[AES256_GCM,data:3aa96Gm9JhSy5/7D47Pv7g==,iv:hPvfQLTDLYYx2x2glucq1ZNJIZ6uYy3con4gwuUFVGI=,tag:+mAS2w1kNZMDmA2s40Q5zw==,type:str]
    country: ENC[AES256_GCM,data:UtqWACSuu0NjxVU=,iv:blO2ThR6sXrHXhNfApX7sB0s3BzLg9+d21UJ/zhTMnA=,tag:Zp/dG8q2gHGAyj08/SvNaA==,type:str]
    latitude: ENC[AES256_GCM,data:iMUwGvvzIanDtJuB8IAbFd0=,iv:UI6XbrVkcYoC5s+jUjo7agf1snIGWYA4zYir14uTMLE=,tag:tDuP87BY0Uiu3RVrEYDpCQ==,type:float]
    longitude: ENC[AES256_GCM,data:u0SW1sOvz5Ts4XxKRAwtohg=,iv:leA6a9l5MJmbGFsDxH2ojG5+OxXJtHi1GuIwZ6F/tNA=,tag:qro5nqObf+u0avCBoKWpHQ==,type:float]
sops:
    age:
        - recipient: age1273kns0xuqdzq9m7eclvvuh0hyt7r9knsn294akxra3fhef6df5q6jqd7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU0VEN0hETmJLcVVRWmFJ
            MUNWV1g3VU9KQlJzc1VWcllSK2RBd0RXYVZJClFmM0VuQ3MzZmdKT0xmUnJ1Nllq
            L0VUYS9MbmNDb01valdCNVZvWllvVzgKLS0tIGFVWEpueWExMTU0c2lqSUdXc3Zv
            T2xEY1lrRGdvVXdUNTAvU2liY1VtQ0kKBO3GSg91rJgo3uUG2VQBaCiuSB+mAhFD
            4UDsZWWNZIadYGmkH3gURPeeRWhvTLHkrLJcESPbohaQ0v6TyVU+8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T11:55:13Z"
    mac: ENC[AES256_GCM,data:eH3TX/WkMJh+OF6PWReq+lSRkoGSDujK5bPQCbLu6reKHNG8hVgqxZ2eUZesRYrCEclJMM5igpCzlv/iHGAr1xhCzgyHWUC8lasqD4FO9m1HsVLKSrcnVdwwDikTyw3o6WCMSd7EBjBYFpArQifpsLVE8LmCQefNg2ysT8S/lrQ=,iv:cnaYe38Agv8RYs6rxDf/QHElDUr1OltvqWySwxONA9s=,tag:IAqjk4J9AUpuR7++ICARmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
