cf_token: ENC[AES256_GCM,data:PR2dS6AP9HEAwnxfaVzOowEcz7pmgI1m9SPu4unha/AUqw7UACraD6JSP03OKa2vonI/y0+T+5hnTDIwJKCCfAA4Ur1ggCoDunTcW4EjapoxsFMjvytfig3AacWZ8PXCZSRfoEpQyaytWArNosTRWJEKqpjw7JzMwhH9fM5yEj/wC+U4NDzXCazbV67Uyf/PO9S6bgLhkZrYozKBnbw51qui1fVMmsBZVRc3h7XjuLyUwQ2Tp2goWQ==,iv:QhcYjMEpPOkKqxSydmGapUIiDTaG2CiX/PkaRLbm+FU=,tag:7rCkYydqjj8NdY7cjClE+Q==,type:str]
sops:
    age:
        - recipient: age1ak0kclmngm3jjt88y55fzyvwwwf09wxz9yzs0caqln3e6h7dacjq2fw8zm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja2ZKaHFQU2V6VE5oMUV3
            a2F1b3FlR2hCdEpkcjBuNkhPOGJ4ZHdiaDBJCnNLVkk4MkhrWUtSbEh5WWFOM1hM
            S0F5V1Q0NU5GSnJCSUQ4M3VIMjZHemcKLS0tIFFEczN0N0ozb0k3MDMzbmR6b3V6
            Z1N0NXJOamZFcEtuSm5oOHNJWHZKamMKkgiDgpWvtnCy7XeKXTpgIbjjuMXn+XKM
            wiceHowAWt/LSz3lWOQWHTKJdAP5k6RZgrk7cC7fJySayJtoKbZ19w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T10:27:07Z"
    mac: ENC[AES256_GCM,data:EdVAnJjovgv0Zw+BrqyZhUkoSk7Qbjy7OBy92MWzJ7XX+vCsh/urDKp4+CGsj6vyNF3uqWvxDDI1STR1EIuasw+IS0OvGKYA/1rBPJl6OJyxqyF4vgqMxmyh/o3/l3U+L1rZW2y4boJjCOd6aTf3hY7aEOvHn99UkC3eqm3uo/8=,iv:ENdpV1fN5obgwsnWWKqC/CLX9ebm+aTX1JiGFEkPQmk=,tag:9MqXkA/mEKtqGXeZj1uYbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
