home-assistant:
    country: ENC[AES256_GCM,data:G9R+GHM+V3HU5RI=,iv:pg7zwUV6XYNtiGbcgvjttfgr+pYACSGV/S9HT/ivLxk=,tag:RLh/04nq/5k9OYZfsLgLOA==,type:str]
    time_zone: ENC[AES256_GCM,data:cana8JugFt++PRp0X8HKfg==,iv:GxXRe/zpEAaZ8PHj3cWZUUGMDFEXdS+sCjIrABiX5Rk=,tag:LoMsv+rmH9VfZEtnogFzWA==,type:str]
    latitude: ENC[AES256_GCM,data:ReVXf2Sl4gXu6oZAAszzw4M=,iv:xXqliG/PpW5gp9P3C5ABaOS/X+VE4iBMdChPLe8ww1o=,tag:iGClrM4Hb9FLZs+yDEx9Pw==,type:float]
    longitude: ENC[AES256_GCM,data:moo4fr4ZWAVQQDIBthtOK+w=,iv:+loHOZckvwwgIzLIrtLNdyPWuphPURZ7XjfjD+qEp78=,tag:JEkCHWa+3hMBA3H3PUi+eA==,type:float]
sops:
    age:
        - recipient: age1jcvl947fgdrxylahyfh3msqsyjp3twd36fgld2jsnxngm0m2agtqynfn29
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ck5pWXBXemFVK1lFNnA1
            bUprVmIxZjl2NWk1M3g4bW0wQXY3aHFRZDBvCnhabEIzeFd0ajkrVWF2MUNuV0R0
            dUhTOEFzWWpaeEo5TS9ndHpnREhEZVkKLS0tIG54NGg3U3JKRVIvQTd4QlhBYkRR
            QkJJRGd2TGE1WFBrQWI1cy9za0M4UmsKquy1klx7gT4+oH8x+f7dAFmoA0EPc7vi
            EMBPAzJ9uQQm3pFr4C26VEkakqqoweasmorUtxlraV9R8PMfCLcs0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T09:35:24Z"
    mac: ENC[AES256_GCM,data:6jLtXdHc+qWcErquOF7R+Idbu9Q1HxSf/67K/iNx17e01lkM32a07iQrurrl3+fctO+mb0YZO6L0lxgGiUoE77nGdyb1iwTmmfwWeJJ9lcinSv1SNu0D4+4ZImuX8Ilu9SicW0L6hN4AS+o8IyohX10SU/Vvqe7yIN3PH55miEs=,iv:0d+hVt06rx1OAPt0IspHddg6bnmilLwQW6VwSt6Co0Q=,tag:qYCHDxkYl5qgNJuFRk01Ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
