{
  flake.nixosModules.lenovo-laptop-config = {
    pkgs,
    lib,
    ...
  }: {
    boot = {
      kernelModules = ["coretemp"];
      loader = {
        systemd-boot.enable = false;
        grub = {
          enable = true;
          device = "nodev";
          efiSupport = true;
        };
        efi.canTouchEfiVariables = true;
      };
    };

    environment.etc."sysconfig/lm_sensors".text = ''
      # Generated by sensors-detect on Sat Aug 15 08:05:27 2026
      # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
      # be loaded/unloaded.
      #
      # The format of this file is a shell script that simply defines variables:
      # HWMON_MODULES for hardware monitoring driver modules, and optionally
      # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

      HWMON_MODULES="coretemp"

    '';

    networking.hostName = "lenovo-laptop";
    time.timeZone = "Europe/Nicosia";
    hardware.nvidia = {
      open = true;
      modesetting.enable = true;
      powerManagement = {
        enable = true;
        finegrained = true;
      };
      prime = {
        offload = {
          enable = true;
          enableOffloadCmd = true;
        };
        intelBusId = "PCI:0:2:0";
        nvidiaBusId = "PCI:1:0:0";
      };
    };
    services = {
      xserver.videoDrivers = ["nvidia"];
      # rsync = {
      #   enable = true;
      #   jobs.music = {
      #     destination = "/home/mridula/backups";
      #     group = "users";
      #     user = "mridula";
      #     sources = [
      #       "/home/mridula/Documents/Music"
      #     ];
      #   };
      # };
      # rsyncd.enable = true;
    };
  };
}
