home-assistant:
    country: ENC[AES256_GCM,data:8Ohhw9tHxyd27i8=,iv:ACF6FDJhJtiQ01mdYUQmCRrzabUq2cTe6Q3CgyZ20Is=,tag:DMj/RPz0iUD/fR6GaAOv9Q==,type:str]
    latitude: ENC[AES256_GCM,data:F0HGxMHj9gqaoZr5TkFslzU=,iv:LNYvJFO9zStnyXzqnrEBGVY9vw4AZ1XSEX9g7pcuGm0=,tag:I98mnRdfaJ73dQ+b0eG/fA==,type:float]
    longitude: ENC[AES256_GCM,data:nWUvhz1vMDjM8y8q+lxb40s=,iv:mG8Qb7yI8HFnkEaUWTEgqGRf7xf5AGOglGCni1wpf4s=,tag:Jaz9KA5kCwqq8w/gZcqk4w==,type:float]
    time_zone: ENC[AES256_GCM,data:6ayd2DT4q/jH02Flvtffug==,iv:dn3ZsV6Y5W6ipMfPCqPJWzZf7Zfgj9uvL92Tjy1o5K8=,tag:F8SYKsjN6Hj2/fepVmLAPQ==,type:str]
sops:
    age:
        - recipient: age17c22cuzyny3t6ctz4qa9qev4yf3r7r82qmvpd8ua8wnkegvkru6q0grhqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQXVYdUtQMWlSNjFYQ0ZX
            cUFQRTB0ZzQrbmdPY3dJa3MxSktXcjJaNUZZCml1cHhjVFBIZXQxTmZFbTBlMDlG
            V09DSm5qOVBCVHQyeFNqbVhBN1YzVEEKLS0tIHN3NStROS9vcVBSMlpoam5UUGk5
            aWdoUjNEQjhGR2w2VVYzNWFoaXRMR1UKSvYChRWuO2Cv8Ez3pU70iD/cMW7NHNn6
            uTDZ0sBu/NtvlVO9qaQzrFSsJmkUgt7FWoLGRdtGnBJqxUpnb6KEqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T09:50:32Z"
    mac: ENC[AES256_GCM,data:S+qzy9I4DY7NM0IiZHYd0p6+SRbfbDUDLM5429G1SAvCMk/4y/V9s/jdippFJ10H7VNjRJRq0EKRl4n3ASqEDXOYk2CUlplvdSHqXTvhqJYhfFS6qcoCDTZX05xCPUXsR0cUukNMztPLjZXOK2kZtKs693NKTClwNhNXcodtOfo=,iv:CWTzgeB8G9z31L4nC/zOBBY3y20g4EB8Ewe+EuNUb3c=,tag:TkgBIptuqdnEchv6E+XtAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
